### ISSUE TITLE
Login lasts 5 minutes

### ISSUE THREAD

**Issue by ThePokeX** [felixrupp/user_cas#10]
- What led up to the situation?

Logging into owncloud and using the service longer than 5 minutes (it is exactly 5 minutes, I have timed it).

- What was the outcome of this action?

Logged me out and created this line in the log: `{"reqId":"qEPU\/53qGS7caCSZU7lT","remoteAddr":"x.x.x.x","app":"core","message":"Login failed: 'xxxxxx' (Remote IP: 'x.x.x.x')","level":2,"time":"2017-08-09T18:12:03+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xxxxxx"}`
There were also owncloud client errors before being pushed to the log in screen, such as not being able to refresh.

- What outcome did you expect instead?

To remain logged in for the time specified by the CAS server

It's very possible this is due to a configuration error, but I have spent a considerable amount of time trying to find the cause of this to no avail.

**Comment by felixrupp** [comment]
Hello @ThePokeX,

can you briefly describe your server and OnwCloud environment?

I have had OnwCloud version specific issues with with the internal login mechanism, which had nothing to do with the user_cas app or the CAS instance at all. In most cases the user_cas app just exited within the OC internal login algorithm. In some cases a 500 server error was raised, in other cases the apache2 threads were just terminated with a segmentation fault.

These issues mostly occured in older 9.xx and versions installed with a linux package manager. The most recent OC 10 Version does not show these issues to me.


Thank you

Felix

**Comment by ThePokeX** [comment]
After updating Owncloud to 10 and your app to the release branch I have not encountered this issue. I will comment again if it crops back up. Thank you!

**Comment by felixrupp** [comment]
Okay, thank you for your feedback!
