### ISSUE TITLE
Update for NC v22 ?

### ISSUE THREAD

**Issue by washidepl** [felixrupp/user_cas#102]
Can we expect new update for nc 22? of course without problems wit DC client on Windows.

**Comment by CorentinS6** [comment]
# set appinfo/info.xml line 33 to
` <nextcloud min-version="14" max-version="22"/>`
works for me

**Comment by ed-ud** [comment]
Seems to work for me with v23 as long as I override phpCAS (I'm using current phpCAS "master").

**Comment by felixrupp** [comment]
Thanks for your contribution, I just released a bumped version including support for up to nextcloud 24.
