### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by IvanovSerg** [felixrupp/user_cas#14]
When I try to set up the user_cas app to my ownCloud without properly tuned phpCAS or I just wanna set it up later with custom folder path  then I got the 500 error.
lib/Service/AppService.php:
$this->casPhpFile = $this->config->getAppValue('user_cas', 'cas_php_cas_path', '');
if (is_string($this->casPhpFile) && strlen($this->casPhpFile) > 0) {
            \OCP\Util::writeLog('cas', 'Use custom phpCAS file:: ' . $this->casPhpFile, \OCP\Util::DEBUG);
            require_once("$this->casPhpFile");
        } else {
            require_once(__DIR__ . '/../../vendor/jasig/phpcas/CAS.php');
        }
After ownCloud installation I modify directly the table params in DB otherwise crashes the whole application

**Comment by felixrupp** [comment]
Hi @IvanovSerg 

it seems, that you did not install user_cas correctly. The correpsonding line of code loads the phpCAS library, which is shipped within the composer dependencies. If you downloaded the release-archive from github, the phpCAS dependency is already included. 

If you installed via *git clone*, you have to resolve the composer dependencies with *composer update*.
Without a phpCAS library, the user_cas app cannot work. After correct installation, you can provide a custom phpCAS Library in the settings.


Greetings

Felix

**Comment by felixrupp** [comment]
Closed as for inactivity. Please open a new Issue, if you still have problems!
