### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by nmd28** [felixrupp/user_cas#15]
Hello.
I follow the step here and when I try to open the administration panel, nothing happen. It's start after I add the user_cas. I get this php error : Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
Any advice ?

Thanks

**Comment by felixrupp** [comment]
Hi @nmd28 

the error you are refering to is a JavaScript error which has nothing to do with the user_cas app.

What exactly is working/not working? Which OC, user_cas and phpCAS versions are you using? Which PHP version are you using?


Greetings

Felix

**Comment by nmd28** [comment]
Hi. 
I'm using OC 9.1.7, php 7.1, the last version of user_cas, phpCAS 1.3.5. I'm really new with this stuff.
Thanks for replying

**Comment by felixrupp** [comment]
Hi @nmd28 

I am afraid, you're using an outdated user_cas version. You have to manually overwrite the existing old 1.3.5 version with my current 1.4.x version. You can grab it on the [release-page](https://github.com/felixrupp/user_cas/releases)

Please report back when you tried that version.

Regards

Felix

**Comment by nmd28** [comment]
Hi Felix,
Massive thanks for your help. It work !

**Comment by felixrupp** [comment]
Hi @nmd28 

no problem, have fun using the app and report any bugs you can find!

Regards,
Felix

**Comment by nmd28** [comment]
Hi Felix. Sorry for the late. 
Here it is : 

{"reqId":"QbPY7TloqiIV0mrZqr13","remoteAddr":"ipAdresse"app":"PHP","message":"session_destroy(): Trying to destroy uninitialized session at \/var\/www\/html\/owncloud\/apps\/user_cas\/vendor\/jasig\/phpcas\/source\/CAS\/Client.php#3683","level":3,"time":"2018-01-16T14:42:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/user_cas\/login?redirect_url=%2Fowncloud%2Findex.php%2Fapps%2Ffiles%2F%3Fdir%3D%2F%26fileid%3D25&ticket=ST-16-qjrVHX9MUANzIKwRWxrG-...............","user":"--"}
{"reqId":"mFbCbVo1nr3YwWgV45yM","remoteAddr":"ipAdresse","app":"cas","message":"phpCAS user password has been checked.","level":3,"time":"2018-01-16T14:42:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/user_cas\/login?redirect_url=%2Fowncloud%2Findex.php%2Fapps%2Ffiles%2F%3Fdir%3D%2F%26fileid%3D25","user":"--"}
{"reqId":"uNZpRueaWue2fdplvaSR","remoteAddr":"ipAdresse","app":"cas","message":"phpCAS user password has been checked.","level":3,"time":"2018-01-16T14:42:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/?dir=\/&fileid=25","user":"user"}
