### ISSUE TITLE
Fatal PHP errors in apps/user_cas/lib/Service/AppService.php

### ISSUE THREAD

**Issue by reswild** [felixrupp/user_cas#22]
When I installed this app today on my Nextcloud 13 site, it took down my whole site because of a PHP error. The error I got in my log was:
`syntax error, unexpected ':', expecting ';' or '{' at /var/www/nextcloud/apps/user_cas/lib/Service/AppService.php#710`

Removing all the references to bool and string from the code solved the issue.

**Comment by felixrupp** [comment]
Hi @reswild 

thanks for your feedback, obviously these were auto generated with the setters/getters. The problem is, at least the type hints on getters are only available in php > 7.

I removed the hints, fix will be up with version 1.5.1 by the end of the day.


Thanks,
Felix

**Comment by felixrupp** [comment]
1.5.1 is released and fixes this issue
