### ISSUE TITLE
Fails code integrity check in Nextcloud

### ISSUE THREAD

**Issue by reswild** [felixrupp/user_cas#23]
I'm getting a 'code integrity check' warning in Nextcloud after installing this app. The error I'm getting is:
```
- user_cas
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
```
I'm running Nextcloud 13.0.4, and the version of user_cas is 1.5.0 (downloaded from https://apps.nextcloud.com/apps/user_cas).

**Comment by felixrupp** [comment]
Hi @reswild 

thanks for your feedback, I don't have any problems on my 13.0.3 instance, will check this. As I am releasing a 1.5.1 today, I will fix the signature with the release!


Regards,
Felix

**Comment by felixrupp** [comment]
1.5.1 is released and fixes this issue
