### ISSUE TITLE
Not able to re-direct to the Nextcloud page after the authentication

### ISSUE THREAD

**Issue by karankotz** [felixrupp/user_cas#25]
Hi, 

I have installed the user_cas app in the nextcloud, here is the following configuration.

1>
<img width="967" alt="screen shot 2018-07-09 at 9 08 00 pm" src="https://user-images.githubusercontent.com/19654061/42483553-30704afe-83bc-11e8-8511-aa050b2aa21c.png">

2>
<img width="971" alt="screen shot 2018-07-09 at 9 09 11 pm" src="https://user-images.githubusercontent.com/19654061/42483585-6130dd98-83bc-11e8-84de-11122435d495.png">

After hitting the cas login, I will be redirected to the CAS server login page but am not able to get redirected back to the nextcloud, after logging in with the test user "casuser" and password "Mellon".

The page just reloads as in the following screenshot:

<img width="858" alt="screen shot 2018-07-09 at 9 11 42 pm" src="https://user-images.githubusercontent.com/19654061/42483649-b9ec857c-83bc-11e8-8639-ab8438a0dcdb.png">

**Comment by karankotz** [comment]
@felixrupp Can you please check this?

**Comment by felixrupp** [comment]
Hi @karankotz 

it seems, that your CAS-Server configuration is not correct. The URL is correctly built (the service URL parameter is set according to your user_cas settings), which implies, that user_cas ist working as it should.

Please check your server configuration for redirecting back to the service.

Regards,
Felix

**Comment by karankotz** [comment]
@felixrupp I am using apereo can server and have not changed any of the configurations. I have just started the server, in order for this app to work, can you please tell me what other configurations should be changed?

**Comment by karankotz** [comment]
@felixrupp Thanks for the advise, I have changed it to 2.0 without any luck. I am running the CAS server via a docker image.

**Comment by felixrupp** [comment]
@karankotz 

And your ownCloud instance is in the same Docker container? If not, you have to configure your Docker containers accordingly, so the communication between both containers is possible. As I am not a Docker expert, I can not help you with Docker itself.

What you can try: Please set the Service URL in the user_cas settings panel to the URL of your ownCloud instance (with correct port). The url must end with "/apps/user_cas/login". 

Regards,
Felix
