### ISSUE TITLE
Question: Is mobile client login possible/supported?

### ISSUE THREAD

**Issue by Jutosa** [felixrupp/user_cas#28]
Are mobile clients supported by user_cas?

When I try to connect to my server using the mobile client.

I get redirected to (e)cas to authenticate in a web view.  After authentication I get redirected to my Nextcloud instance but the login isn't successful and I can't log in.

The server log says that authentication was successful. The user can be logged in in the browser.

**Comment by felixrupp** [comment]
Hi @Jutosa 

mobile client login is supported via the oauth2 app from ownCloud. You need to activate the oauth2 app in your ownCloud/Nextcloud instance, afterwards the mobile client login also works via oauth2 and CAS.


Regards,
Felix
