### ISSUE TITLE
Documentation says git/composer is optional but lacks other instructions

### ISSUE THREAD

**Issue by WingsLikeEagles** [felixrupp/user_cas#29]
The documentation clearly states that using composer with git is an optional installation method.  But, there are no other instructions how to install it without composer/git.
This is important for people who are installing in a docker container and do not wish to have git installed.

**To Reproduce**
1. Read Installation at https://github.com/felixrupp/user_cas
2. Notice line "Optional: Composer Dependency Manager, if you want to install via GIT." and "perform a composer update command"
3. Notice the lack of instructions other than "GIT: STEPS"
4. Notice no instructions for installing dependencies or even what the dependencies are.

**Expected behavior**
Please add instructions to install dependencies in a method other than using Git.

**Software (please complete the following information):**
 - Server-OS: Any
 - HTTP-Server Version: Any
 - PHP-Version: Any
 - phpCAS-Library-Version: Any
 - ownCloud/Nextcloud Version: Any
- user_cas-Version: 1.5.3

**Comment by felixrupp** [comment]
Hi @WingsLikeEagles 

I added two sections in the readme describing how to install via ownCloud market or the release tarballs.

If you still need more information on how to install OR you can provide additional information/tips, please fork and do a pull request on the readme!

Thanks for your feedback and regards,
Felix

**Comment by WingsLikeEagles** [comment]
Hello Felix,

Thank you!  I will check it out.  I was able to get things up and
running... but I changed so many settings it's hard to tell what
combination of things fixed it.  I am trying to document it in case I need
to reinstall. So I will provide any feedback I learn.

Thank you,
Justin
