### ISSUE TITLE
Should user_cas 1.5.5 work with NC14?

### ISSUE THREAD

**Issue by brtptrs** [felixrupp/user_cas#31]
**Describe the bug**
On Nextcloud 14 the app does not seen to work properly. 

**To Reproduce**
- On login the user just gets the normal login page, with no option to use cas.
- When I call the cas login page manually https://my.nextcloud.xyz/apps/user_cas/login the app sends me to my cas server for authentication as expected. 
- However after being sent back to Nextcloud with my auth-token the ticket does not seen to get processed. 
- The user is not authenticated and gets sent back to the normal login page when other urls are called 

**Expected behavior**
Authenticate a user against a cas server

**Software:**
 - Server-OS: Ubuntu 18.04
 - HTTP-Server Version:Apache 2.x
 - PHP-Version:PHP 7.1
 - phpCAS-Library-Version: Default from the app
 - Nextcloud Version 14.0.0
- user_cas: user_cas 1.5.5

**Additional context**
Numerous other apps works as expected with our CAS server

**Comment by felixrupp** [comment]
Hello @brtptrs 

I am going to check the described behaviour today and will report back!


Regards
Felix
