### ISSUE TITLE
To much information in INFO Log

### ISSUE THREAD

**Issue by grischdian** [felixrupp/user_cas#33]
**Is your feature request related to a problem? Please describe.**
On our production system we see for each login multiple user_cas entries in owncloud.log which are not relevant to an Error. oC is configured to 'loglevel' => 3

In my opinion these logentries are better in level debug then in Error or Info 

**Describe the solution you'd like**
Change logentries which are not related to an error to debug.

**Describe alternatives you've considered**
Change logentries which are not related to an error to info

**Comment by grischdian** [comment]
I mean really A LOT entries... almost 410k in 3 months.

**Comment by felixrupp** [comment]
Thanks for your input @grischdian, your pull request has been merged!
