### ISSUE TITLE
Broken public share

### ISSUE THREAD

**Issue by landryb** [felixrupp/user_cas#37]
**Describe the bug**
Slightly similar to #35 but not exactly the same, if nextcloud is hosted at the root of the webapp and  `user_cas` is enabled (with login enforced), here with php 7.2 the public share links starting with `/s/` are broken because they redirect to the cas login page.

The logic needs to be fixed on https://github.com/felixrupp/user_cas/blob/master/appinfo/app.php#L31 as `strpos($requestUri, "/s/")` will return 0 on `requestUri=/s/XGJP8SJi7DNnddw` and thus be considered false, and trigger the redirection to auth cas.

I locally modified the test to be `strpos($requestUri, "/s/") !== FALSE` and it seems to fix the issue. Dunno if other sub-uri tests should also be fixed, but i can do a PR if this fix makes sense to you.

**Software (please complete the following information):**
 - Server-OS: stretch
 - HTTP-Server Version: nginx
 - PHP-Version: 7.2
 - phpCAS-Library-Version: [e.g. phpCAS  1.3.5]
 - ownCloud/Nextcloud Version: 14.0.3
- user_cas-Version: 1.5.6

**Comment by landryb** [comment]
Note that with this fixed, #35 still exists as no js/css is displayed when the unauthenticated user gets to the public share.

**Comment by felixrupp** [comment]
Working on that!

**Comment by felixrupp** [comment]
@landryb 

In the current 1.6.0 release (https://github.com/felixrupp/user_cas/releases/tag/1.6.0) the activation of the app is completely rewritten and will hopefully not break other apps/functions anymore.

Please test that and report back if you still have issues!

**Comment by landryb** [comment]
confirmed working fine with 1.6.0, public shares are accessible even if cas login is enforced
