### ISSUE TITLE
user_cas breaks Nextcloud when theming is used

### ISSUE THREAD

**Issue by centredecalcul** [felixrupp/user_cas#38]
**To Reproduce:**
1. Fresh install with user_cas and user_ldap working good
2. Modify the site name with Theming app
3. Try to log on
4. Only a blank page is shown
5. Disable user_cas for Nextcloud to work again

**Software:**
 - CentOS 7.5
 - Apache 2.4.6-80
 - PHP 7.1
 - Nextcloud 14.0.3
 - user_cas 1.5.6

**Log:**

{"reqId":"W-P9ciu753Xmiw8mvOPx2AAAAAA","level":3,"time":"2018-11-20T12:26:26+00:00","remoteAddr":"1.2.3.4","user":"abcdLogin","app":"PHP","method":"GET","url":"\/","message":"Declaration of OCA\\UserCAS\\User\\Backend::checkPassword($uid, $password) must be compatible with OCP\\User\\Backend\\ICheckPasswordBackend::checkPassword(string $loginName, string $password) at \/var\/www\/owncloud_dev\/nextcloud-14.0.3-20181120\/apps\/user_cas\/lib\/User\/Backend.php#45","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"14.0.3.0"}

**Comment by reswild** [comment]
It's odd that this happens only when using the Theming app. In any case, this patch should take care of that error: https://github.com/reswild/user_cas/commit/5130f5bd1a5718f12c90e61cc03ec410ad65f1b7

**Comment by centredecalcul** [comment]
It works, thank you !
