### ISSUE TITLE
user_cas ask for credentials every five minuts after user is loged in

### ISSUE THREAD

**Issue by JuanjoUAB** [felixrupp/user_cas#42]
**Is your feature request related to a problem? Please describe.**
When desktop and mobile clients loged in through user_cas and we have as mandatory user login with CAS, after five minutes it asks for credentials because the client has lost the user_cas token. This behaviour is repeated every five minuts.

**Describe the solution you'd like**
When these two clients are loged for the first time we think the normal behaviour is stay loged and not ask for credentials every five minutes meanwhile the token is valid.

**Describe alternatives you've considered**

**Additional context**
We have in our infraestructure a CAS server version 4.2.1. This server supports CAS 1, 2, and 3 protocols.

Our user_cas app in our NextCloud instance parameters are:
CAS Server version: CAS 2.0
CAS Server Hostname: xxxxx
CAS Server Port: 443
CAS Server Path: /p3 (this parameters is for force the CAS 3.0 protocol)

**Comment by reswild** [comment]
I made a quick fix for this problem earlier, but it seems that stopped working on Nextcloud 14. Here is another attempt: https://github.com/reswild/user_cas/commit/cdcb8bfafddb73eea69456abc483c6a867884a26

**Comment by felixrupp** [comment]
Warning, @reswild 's fix is only working with Nextcloud but breaks ownCloud functionality because of different APIs. I am working on a better solution to implement both variants.

**Comment by felixrupp** [comment]
PS.: @JuanjoUAB The phpCAS library behind user_cas does not support CAS 3.0 protocol.

**Comment by reswild** [comment]
I thought phpCAS did support the CAS 3.0 protocol. At least https://github.com/apereo/phpCAS/pull/116 suggests it does.

**Comment by felixrupp** [comment]
Yes you’re right, I totally missed this out. I will add the 3.0 option right away.

**Comment by felixrupp** [comment]
@JuanjoUAB 

In the current 1.6.0 release (https://github.com/felixrupp/user_cas/releases/tag/1.6.0) the activation of the app is completely rewritten and will hopefully not break other apps/functions anymore.

Please test that and report back if you still have issues!

@reswild CAS 3.0 is implemented too!

**Comment by landryb** [comment]
To have cas login/logout working fine, i have to modify https://github.com/felixrupp/user_cas/blob/master/appinfo/app.php#L35 and remove `/index.php` from both `/login` & `/logout` tests.

**Comment by felixrupp** [comment]
@landryb Thanks for your feedback. Obviously Nextcloud (your are using Nextcloud, right?) has another route for the login view. I am going to add the /login route this evening.

Regarding your 5min redirect problem: I recovered the changes commited by @reswild, unfortunately they were ommited while merging other commits.

New bugfix release will be there this evening.

**Comment by landryb** [comment]
Yes that's on nextcloud 15.0.2 - thanks for the fast response, much appreciated :)

**Comment by felixrupp** [comment]
@landryb 1.6.1 is up, please test it and report back if there is still an issue!

**Comment by landryb** [comment]
1.6.1 seems to be fine, i've been a bit surprised to see the `/logout` test removed in 00d5de85 but i guess it's not used, as the login/logout part works fine here - and no annoying disconnection after 5mn timeout. thanks !

**Comment by felixrupp** [comment]
@landryb /logout check is gone, because the hooks are now registered outside (above) this line. There is no need to check further for a login on the `/logout` route.

**Comment by landryb** [comment]
Sadly, i wonder if we should reopen this issue, because i'm still experiencing it with NC 15.0.5 & user_cas 1.6.1... I'll retest after reinstalling the app from scratch but something feels fishy.
