### ISSUE TITLE
CAS Attributes not readable anymore

### ISSUE THREAD

**Issue by felixrupp** [felixrupp/user_cas#48]
**Describe the bug**
CAS user attributes are not readable anymore in my production environment.

**To Reproduce**
1. Log in via CAS
2. Look into the phpCAS debug file
3. See that there are no attributes

**Expected behavior**
See all expected Attributes, that are retrieved by other apps using the same version of phpCAS Library in my ecosystem.

**Software (please complete the following information):**
 - Server-OS: Debian 9
 - HTTP-Server Version: Apache2
 - PHP-Version:  PHP 7.0
 - phpCAS-Library-Version: phpCAS  1.3.6
 - ownCloud/Nextcloud Version ownCloud 10.1.0/Nextcloud 15.0.2
- user_cas-Version: user_cas >=1.6.0

**Additional context**
Two other apps using the same 1.3.6 version of the phpCAS Library are retrieving the attributes, user_cas does not.

CAS-Server is a black-box for me, so I can not change the server config.

**Comment by felixrupp** [comment]
Anyone else having problems retrieving attributes since 1.6.0?

**Comment by landryb** [comment]
Using CAS 2.0, attributes are still working fine for me with 1.6.0 & 1.6.1, and i see them listed in the debug file (/tmp/nextcloudcas.log here)

**Comment by felixrupp** [comment]
Thanks for your feedback, must be a server side issue. I try to contact our sysadmin on that.

**Comment by felixrupp** [comment]
Works again for me with no obvious reason.
