### ISSUE TITLE
Code enhancements ...

### ISSUE THREAD

**Issue by DeepDiver1975** [felixrupp/user_cas#5]
1. use info.xml for settings
instead of https://github.com/felixrupp/user_cas/blob/master/appinfo/app.php#L43 you can define settings via the info.xml - example is here https://github.com/owncloud/core/blob/master/apps/files/appinfo/info.xml#L37-L39

2. use config option to setup alternative logins - instead of https://github.com/felixrupp/user_cas/blob/master/appinfo/app.php#L54 see https://github.com/owncloud/core/blob/master/config/config.sample.php#L211-L218

**Comment by felixrupp** [comment]
Hi @DeepDiver1975 

thank you for your input :) ! Always appreciate such hints!


Greetings

Felix
