### ISSUE TITLE
Create/update user server side

### ISSUE THREAD

**Issue by pmayer** [felixrupp/user_cas#50]
Hi @felixrupp,

what's the best way of creating or updating a user for the user_cas backend server side? Should I use the occ user commands?

Thank you for your help!

**Comment by felixrupp** [comment]
Hi @pmayer,

the best-practice for a clean ownCloud/Nextcloud instance where you need to create the users is, that you simply set the:
- Autocreate user after first CAS login?
- Update user data after each CAS login?
options in the user_cas backend. With that each of your CAS-users is able to login and each of them will get their accounts created on the fly on login. If you want to restrict the logins to specific groups your CAS instance is communicating, please make use of the authorization feature in the user_cas backend:
- Authorized CAS Groups

./occ commands are not compatible with user_cas, they are only for usage with the default Database backend.

I hope I could help you. Please report back if you still have questions!


Regards,

Felix

**Comment by pmayer** [comment]
Hi @felixrupp,

thanks for the answer, but unfortunately that doesn't solve my problem, because it requires each user to log in him/herself. In my use case another system with CAS login is creating and sharing folders with users and therefore I need to ensure that the account exists even if that user hasn't logged in to ownCloud before. So I need a way to create accounts beforehand – what would be the best way to achieve that?

**Comment by felixrupp** [comment]
Hi @pmayer,

okay I understand what you need. Unfortunately and as far as I know, there is currently no way to create users in a different Backend via occ-commands.

I will add this feature to my feature-request-list, but I can not foresee when it will be implemented.

As a workaround, you can add users via occ user-command and change the backend in the database manually to "OCA\UserCAS\User\Backend".

Regards,
Felix

**Comment by pmayer** [comment]
Hi @felixrupp,

alright – thanks for the answer and your help!

Regards,
Philipp

**Comment by felixrupp** [comment]
1.7.0 is released with OCC commands to create and update user_cas users. Please review the readme.
