### ISSUE TITLE
WebDAV/CalDAV

### ISSUE THREAD

**Issue by pmayer** [felixrupp/user_cas#54]
Hi @felixrupp,

is it possible to use user_cas for accessing WebDAV/CalDAV?

Thank you for your help!

**Comment by felixrupp** [comment]
Hi @pmayer,

currently this is not possible with user_cas alone. I have not tested WebDAV with active OAuth2 app. This would be the only possible way of getting a valid authentication from such a client. In this case the WebDAV client App (e.g. on your PC) must be able to use "forms based authentication". 
The WebDAV/CalDAV protocol itself does not use web/html-based authentication panels, but the CAS server is just that, a form based web-frontend for authentication.

As a workaround, all ownCloud users created and authenticated by user_cas, can set a custom local ownCloud password in the ownCloud user settings, to use with client authentication (also WebDAV, CardDAV and CalDAV).


Regards,
Felix

**Comment by pmayer** [comment]
Hi @felixrupp,

alright – thanks for the answer. According to https://github.com/owncloud/oauth2/issues/201 it's not possible with OAuth2 as well.

Regards,
Philipp
