### ISSUE TITLE
Disable change password for CAS users

### ISSUE THREAD

**Issue by Baso123** [felixrupp/user_cas#55]
Hi,

I have setup owncloud 10 (10.0.10.4) with the cas App (1.6.1).
It is working fine.

However, it appears that users (OCA\UserCAS\User\Backend) have the ability to change the owncloud local (OC\User\Database) password via Personnal/settings. It is generating confusion to users. 

Is there a possibility to "Disable change password" for CAS users (OCA\UserCAS\User\Backend)

Note : I have users configured with IMAP Backend. For these IMAP users,  change password is automatically disabled in Personnal/settings.

Thanks

**Comment by felixrupp** [comment]
Hi @Baso123,

there is a reason, why you are able to set a local ownCloud/Nextcloud password for user_cas users. That is, that WebDAV and CalDAV don’t work with form-based-authentication services like the CAS-server. To be able to use CalDAV for example, the users have to set a local password, too!

Disabling that, would break the Calendar and Contacts feature for user_cas users.

IMAP as a backend can obviously be used without a form-based-authentication, that is why you don’t need a local ownCloud/Nextcloud password to authenticate for WebDAV/CalDAV via IMAP.


Regards,
Felix

**Comment by Baso123** [comment]
Hi,

Thanks for the quick response.

I am using the Owncloud **App passwords** for :
> Owncloud PC client
> Davdroid Mobile client (CalDav & Contacts)

I believe that App passwords are meant to be used for the non-web access. 

With CAS performing the web-access authentification, the owncloud local (OC\User\Database) authentification can be considered useless for my implementation.

That is why I suggested the  "Disable change password" for CAS user owncloud local (OC\User\Database) password.

May be it could be a checkbox Option "Disable change password" 

Thanks & Regards,

**Comment by felixrupp** [comment]
Hi @Baso123,

I understand what you’re doing and yes, in your usecase disabling the "change-password“ field would be a reasonable thing. But at the moment I can’t tell you if this would be a possible solution, because the editable fields for the user in a backend are hardcoded in the class defintion of the corresponding backend. So I would need to engineer an option-checkbox which changes the contents of a class-file. 

That’s currently too complicated and time consuming! Sorry!


Regards,
Felix

**Comment by Baso123** [comment]
Hi,

I fully understand the situation.

Thanks for this great Cas_user

Rgds,
