### ISSUE TITLE
user_cas UI (CAS Login) disappears when theming is applied

### ISSUE THREAD

**Issue by biocoder** [felixrupp/user_cas#60]
**Describe the bug**
user_cas works as expected on fresh install but the login UI/UX disappears after theming. I tried the patch that is mentioned here (https://github.com/felixrupp/user_cas/issues/38) and changed line 88 on lib/User/Backend.php as mentioned but it does not fix anything.

**To Reproduce**
Downloading and enabling user_cas works fine on default Nextcloud 16 install, but the UI "CAS Login" below the default login disappears after theming the Nextcloud install. Removing and reinstalling does not fix the issue, so I checked "Force CAS login" for now. I do not see any error in the log file. I cannot troubleshoot. Any ideas what might have happened?

**Software (please complete the following information):**
 - Server-OS: Ubuntu 18.04
 - HTTP-Server Version: Apache 2.4.29
 - PHP-Version: PHP 7.3
 - phpCAS-Library-Version: phpCAS  1.3.5
 - ownCloud/Nextcloud Version: Nextcloud 16.0
- user_cas-Version: user_cas 1.7.1

**Comment by felixrupp** [comment]
Hi @biocoder 

_lib/User/Backend.php_ is not used by Nextcloud, it’s for ownCloud only. For Nextcloud there is the Backend _lib/User/NextBackend.php_ where the declaration is already patched as described in #38. I am currently testing the bug. Please stand by!

Regards,
Felix

**Comment by felixrupp** [comment]
Hi @biocoder 

I fixed the bug, it will be included in Release 1.7.2, coming the next days. 


Regards,
Felix

**Comment by biocoder** [comment]
Awesome! You rock. I will test it out once released.
