### ISSUE TITLE
Error: Internal script failure

### ISSUE THREAD

**Issue by soda31** [felixrupp/user_cas#62]
Hello,

I have a critical problem to use user_cas app

As I was not sure that the problem was linked to my platform I use nextcloud demo to reproduce problem

* I go to https://nextcloud.com/ and click on "demo" to create a new instance of nextcloud

* As an administrator I download + install "CAS user and group backend" application

* I go to cas parameters 
https://demo.nextcloud.com/xxxxx/settings/admin/security

* I enter CAS server host , save and logout

At login page I choose "CAS" and got 
Error: Internal script failure

So at this step unable to relogin even with normal auth fields

Same thing if no fields in cas app are set up

What I do wrong ?

Thanks !

**Comment by felixrupp** [comment]
Hi @soda31 

I am currently checking this out. Please standby.

**Comment by felixrupp** [comment]
@soda31 
I don’t have any problems when entering the CAS host, port and server path. Did you fill in all necessary information? Please refer to the readme, if you are still unclear.


Regards,
Felix

**Comment by soda31** [comment]
Hi Felix,
Thanks for your help !

I made a little video showing error message.
I enter nothing in CAS information plugin and was unable to log to nexcloud again.
[](https://youtu.be/5JPhS9nC0V8)

Enrique

**Comment by felixrupp** [comment]
@soda31 
Thanks for the video, now I know what you meant. I am going to add some error handling here for possible incomplete setups!

Thank you!

**Comment by soda31** [comment]
👍

**Comment by felixrupp** [comment]
@soda31 
Should be fixed with [Release 1.7.2](https://github.com/felixrupp/user_cas/releases/tag/1.7.2)
