### ISSUE TITLE
Group not created / associed

### ISSUE THREAD

**Issue by sparadrus** [felixrupp/user_cas#63]
Hi,
When a CAS User logon, this Name and Mail are correctly retrieved and updated from CAS Attributes, but the memberOf attribute not.
CAS send this format of group (from AD) :

memberOf=CN=ADM-Informatique,OU=MyOU,DC=DOMAIN,DC=LAN

I don't understand.. have you any idea please?
Thanks !

in cas.log :
2019-08-21 19:41:37,729 INFO [org.apereo.cas.authentication.AbstractAuthenticationManager] - <Authenticated principal [mylogin] with attributes [{cn=mylogin, displayName=NAME FAMNAME, givenName=NAME, mail=mail@domain.fr, memberOf=CN=ADM-Informatique,OU=MyOU,DC=DOMAIN,DC=LAN, sAMAccountName=mylogin, sn=FAMNAME}] via credentials [[mylogin]].>

-  Apereo CAS 5.1
 - Server-OS: Ubutnu 18
 - HTTP-Server Version: Apache 2.4
 - PHP-Version: PHP 7.0
 - phpCAS-Library-Version: Your packaged version
 - ownCloud/Nextcloud Version Nextcloud 15.0.0]
- user_cas-Version: 1.7.1

**Comment by felixrupp** [comment]
Hi @sparadrus 

user_cas is currently not able to use custom group attribute’s formats. Also see #51 as a duplicate. You have to change the format of the CAS-Server instance to follow the CAS protocol default.


Regards,
Felix

**Comment by sparadrus** [comment]
Ok thanks and sorry for the duplicate.
Excuse me but what format is excepted for group?
Thanks,
Regards
