### ISSUE TITLE
Multiple AD CLI Import

### ISSUE THREAD

**Issue by sparadrus** [felixrupp/user_cas#65]
Hello,
I have 2 ActiveDirectory (and probaly one openLDAP soon) with one CAS server.
It's possible in future version to have multiple configurable AD servers for Import CLI?
Thanks 
Regards

**Comment by felixrupp** [comment]
Hi @sparadrus 

currently there are no plans to implement multiple LDAP sources. You should more likely configure your CAS server (if you are the admin for all three systems) so you don’t have the need to use the LDAP CLI import any longer.

**Comment by sparadrus** [comment]
Yes but for now I think, with cron, I inject SQL Update script in _appconfig table to change servers value and execute your cli script after that...  It's not beautiful but... I see later for CAS ;)
Many Thanks Felix, I stop answers I promise :)
