### ISSUE TITLE
CLI Import Active Directory does nothing

### ISSUE THREAD

**Issue by sparadrus** [felixrupp/user_cas#66]
Hi Felix,
The cli script for import user don't create or sync user... I have tried all possible combination...
You have test the script on ActiveDirectory or only on openLDAP?
NC 15
User_Cas 1.7.2
Thanks !

sudo -u www-data /usr/bin/php /var/www/nextcloud/occ cas:import-users-ad -d 1 -c 1 -vvv

Start account import from ActiveDirectory.
[info] AD connected successfully.
[info] AD bound successfully.
[info] Init complete.
[info] Getting all users from the AD …
[info] Users have been retrieved.
[info] AD connection closed successfully.
Account import from ActiveDirectory finished.
Start account import to database.
[info] Backend conversion: Backends will be converted to CAS-Backend.
[info] Delta updates: Existing users will be updated.
Account import to database finished.

**Comment by felixrupp** [comment]
Hi @sparadrus 
the import has been tested against an AD LDAP. If your routine does not import any users, the settings to find the correct records is not correct. As I have no knowledge about your LDAP setup and structure, I can not tell you what to configure.

Please make sure your `LDAP Base DN` and `LDAP Sync Filter` settings are correct by testing them on a commandline against your LDAP server.

Regards,
Felix

**Comment by sparadrus** [comment]
Hi Felix,
Ok it work now, in fact all attributes must be in lower case.
Ex : 
cas_import_map_uid : samaccountname
instead of sAMAccountname
All groups are sync it's wonderful...
Thanks !
