### ISSUE TITLE
custom logout page

### ISSUE THREAD

**Issue by mrvcyln** [felixrupp/user_cas#68]
Hi,

When I logout from nextcloud, the cas logout screen comes up. I would like to come back to the nextcloud login screen. How can I do that?

**Comment by felixrupp** [comment]
Hi again @mrvcyln,

as stated before, you have to configure this in your CAS Server. user_cas is setting the `service` parameter already.

Regards,
Felix

**Comment by felixrupp** [comment]
Hi @mrvcyln 

there was actually a bug which prevented the `service` parameter to be appended. Please update to current version 1.7.4 and try again!


Thanks for your input and regards,
Felix

**Comment by felixrupp** [comment]
Hi @mrvcyln 

as per CAS documentation[](https://apereo.github.io/cas/5.1.x/installation/Logout-Single-Signout.html#cas-logout): you "must register the service URL in the service registry of CAS and enabled and CAS must be allowed to follow service redirects."

Please refer to the official CAS Server documentation on how to do it. I can not give support for CAS Server.


Regards,

Felix
