### ISSUE TITLE
Anomalies about code integrity checking

### ISSUE THREAD

**Issue by qw3672939** [felixrupp/user_cas#72]
**Describe the bug**
Prompt that some documents did not pass the preliminary check.

**error code**
`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini
- user_cas
	- INVALID_HASH
		- composer.lock
		- vendor/composer/installed.json
		- vendor/jasig/phpcas/source/CAS.php
		- vendor/jasig/phpcas/source/CAS/Client.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => 0f710c8ef810a26fe64c79abfadf76cc23ece9b4bdfc216f1cb6fce9dba10d9472374e8fe51d835c197ac331f3435a78b4e662b2e7c566cb8fffa11bfcc0770c
                        )

                )

        )

    [user_cas] => Array
        (
            [INVALID_HASH] => Array
                (
                    [composer.lock] => Array
                        (
                            [expected] => 0e6335bd6634aa409f16c3e68ff881c958c6bfcf5a6e6ea3ccc44d17432887b1565807fc2498c156fbd95e9481fb20a68d8841af67d1d53f7ccbaa392f02dc62
                            [current] => 8d1adc2d52ad4f0e12f6afc1340a44bfca61eceb8f0706de5bd47bef1f636548ef596b66d3b80981c029690910c81b18a9bbc6eee23e2b8ad4f7f7c6aeede331
                        )

                    [vendor/composer/installed.json] => Array
                        (
                            [expected] => c08182cfa20ababec397d6f4a3e52217755e413f9b9a3e71e89f116f5bd95b33a72672c8fb33fbcd1bcd5e67d44ddaba71d9585b80f39156a89483a97b2d0997
                            [current] => e06e0c73d9a3acf8fb7a64ed72871ffa960d5457d86ebfb195e21aabe23f34fcf74a2acac4cc764151110c40c7d9f52b69e48433884b0a1ce1bf0ae536a98fd3
                        )

                    [vendor/jasig/phpcas/source/CAS.php] => Array
                        (
                            [expected] => 09ca2a4b18c402d406206a516d0976a704679415aaf0be7e8fe73cd7889272b8192cb45d76c38aa7118d81cbefa884d3f08ece728ed9a5e40e179d79dc2a9f67
                            [current] => eac87e6b61f6babfb1891ca96df3ad7c609b84013682d58d271675f4e2aa8b2ccca87d32c4cd4d60958d693ecfe52710eed9ddfad4b52be8531dd90460e01c9c
                        )

                    [vendor/jasig/phpcas/source/CAS/Client.php] => Array
                        (
                            [expected] => 7c6c043a5372548165dc4ede534fb02003c53a716b95971b0354be574bd5c5fd9509fe5af1d825bcb9f29cb7595a69d0b7c83a636122d6effa7b4cb12156ba93
                            [current] => 14501330d3bfa4c5c4c65f51343f269cf0ab5434e42c624fc6a0b294b553df30dc2b434cd7ed95afe8118778de3b118279fb563463674536ae6a83d8e087e28e
                        )

                )

        )

)`

**Software (please complete the following information):**
 - Server-OS: [e.g. centos 7.6]
 - HTTP-Server Version: [e.g. Apache 2.4.6]
 - PHP-Version: [e.g. PHP 7.2.19]
 - ownCloud/Nextcloud Version [e.g. ownCloud 10.2.1]
- user_cas-Version: [e.g. user_cas 1.7.3]

**Additional context**
Every time you adjust the cas configuration, the above code error message will appear. How do you need to solve it?

**Comment by felixrupp** [comment]
Hello @qw3672939 
first of all you should go into the Settings panel and rescan the files for integrity. I’m also checking the signature for potential errors!

Thanks for the message.

Felix

**Comment by felixrupp** [comment]
Hi @qw3672939 
I double checked the signature of 1.7.3 and 1.7.4. They are both valid. How did you install user_cas? Did you install from ownCloud Market/Nextcloud Appstore?


Regards,
Felix

**Comment by qw3672939** [comment]
> Hello @qw3672939
> first of all you should go into the Settings panel and rescan the files for integrity. I’m also checking the signature for potential errors!
> 
> Thanks for the message.
> 
> Felix


Hello@felixrupp
 I am rescanning the integrity of the file in the settings panel, or always prompt the error.

**Comment by qw3672939** [comment]
> Hi @qw3672939
> I double checked the signature of 1.7.3 and 1.7.4. They are both valid. How did you install user_cas? Did you install from ownCloud Market/Nextcloud Appstore?
> 
> Regards,
> Felix

Hello @felixrupp 
The program is upgraded from 1.7.1 to the 1.7.3 version of the owncloud. After installation, the owncloud code app has no user_cas package by default. I update the user_cas code of clone on your GitHub, and then always prompt the signature. The problem is.

**Comment by felixrupp** [comment]
@qw3672939 So I assume, you are using the 'Git Clone' method to install? This method is only suitable for development purposes, because there is no signature in the Git repository. You have to install via ownCloud Market/Nextcloud AppStore or download the release tarballs from the [release page](https://github.com/felixrupp/user_cas/releases).

I assume this solves your problem. Please report back, if you still have problems.


Regards,
Felix
