### ISSUE TITLE
Cannot set quota for user via cas attribute

### ISSUE THREAD

**Issue by mad61** [felixrupp/user_cas#74]
**Describe the bug**
Cannot set quota for user via cas attribute

**To Reproduce**
1. Configure cas to set attribute 'quota' in response (filled with '0' in my configuration)
2. Configure use attribute 'quota' to set quota for new users
3. Login as user
4. User gets created and logged in but has no quota limit

**Expected behavior**
User should have a "0 B" quota (because read-only user).

**Software (please complete the following information):**
 - Nextcloud 16.0.5
 - user_cas 1.7.4 

**Additional context**
May I found the issue already.

In user_cas/lib/Service/UserService.php the following code exists (from line 492):
`
if ($usersOldQuota < $newQuota || ($usersOldQuota > $newQuota && $newGroupQuota != FALSE)) {
            $user->setQuota($newQuota);
            $this->loggingService->write(LoggingService::DEBUG, "User '" . $uid . "' has new Quota: '" . $newQuota . "'");
        }
`
In my case there is no group quota configured so $newGroupQuota is NULL . This $newGroupQuota variable lets the if-clause always be skipped, so quota will never be set.

**Comment by felixrupp** [comment]
Hi @mad61 

if the user had an individual quota of >0B before, you can not make it smaller via the CAS attribute of the user. This is to protect manual set quotas and only overwrite automatically, if the quota from the CAS server attribute is higher than the manual or group set value in Nextcloud. 

Hierarchy is like in this example:
- Manual set/default quota in Nextcloud: 1GB
- CAS quota attribute is set: check if the attribute quota is higher than the old quota, if yes, replace it
- Group quota is set: take the highest quota of all groups of the user, check if value is higher than the old quota, if yes, replace it
- Attribute and Group quota are set, first set Group quota (like above), then check attribute quota. Attribute quota overrides group quota, if group quota has been set in this update cycle.


If you want to have read only users, I suggest setting the default quota of your Nextcloud instance to 0B and manage all other quotas with group quotas or individual quotas! So you only manage the users who should have write access, and not the ones without.


Regards,
Felix
