### ISSUE TITLE
Button offset on login page

### ISSUE THREAD

**Issue by Ecphrasis** [felixrupp/user_cas#76]
Hi and thank you for this very usefull app !
Since version 18.0, the button is offset in the login page :

![Sans titre](https://user-images.githubusercontent.com/11899009/72849452-f91ebb80-3ca6-11ea-8fbd-69925a45c81e.png)

Maybe related to this bug : https://github.com/nextcloud/server/issues/19049

Thanks a lot !

**Comment by AaronADev** [comment]
This affects both CAS and Registration app, they are both offset. This only started occurring in NC 18 for me as well.

**Comment by felixrupp** [comment]
Hi @AaronADev @Ecphrasis 

this is a bug/problem on the Nextcloud 18 stylesheet. I only register the login button on the Nextcloud, but I don’t have any control over the visual appealing, sorry. Please report the bug, if not already done, to the Nextcloud guys.


Regards,
Felix
