### ISSUE TITLE
CSS doens't apply to the button

### ISSUE THREAD

**Issue by Ecphrasis** [felixrupp/user_cas#78]
Hi,
Little problem : The main CSS doesn't apply to the login button. I have created an issue on the Nextcloud/server Github with a picture, https://github.com/nextcloud/server/issues/19571
They said that the CSS belongs to you. Is there a way to have visual improvement ? Or a CSS block to insert in the app CSS theming https://apps.nextcloud.com/apps/theming_customcss ?
Thanks a lot !

**Comment by felixrupp** [comment]
Hi @Ecphrasis 

I am not applying any CSS to the login screen or any other part of the Nextcloud GUI than the user_cas settings panel in the backend.
The current styling is done by the Nextcloud core CSS. Please refer to these styling blocks to change the appearance of the button via the CustomCSS-App.


Regards,
Felix
