### ISSUE TITLE
CAS authentication over Two-Factor TOTP Provider 

### ISSUE THREAD

**Issue by labrude91** [felixrupp/user_cas#79]
Hello,

I use Nextcloud 17.0.2, I configured Ldap authentication and CAS authentication ( plugin CAS user and group backend 1.8.1). 
I activate Two-Factor TOTP for all users. It works perfectly when my users connect through LDAP, but not with CAS.
In CAS case, the user authenticate and he is directly redirected to it's nextcloud's account.
Have I misconfigured something ?

**Comment by felixrupp** [comment]
Hi @labrude91 ,

no you haven’t. But you have misunderstood the concept of CAS. CAS works as a single authentication system, so if you want a multifactor setup for a CAS based authentication, you have to configure this in your CAS server.


Regards,
Felix
