### ISSUE TITLE
ownCloud add the user_cas

### ISSUE THREAD

**Issue by WylAndy** [felixrupp/user_cas#8]
ownCloud tip: Please use the command line updater because you have a big instance.
I do as this, but it did not work

**Comment by felixrupp** [comment]
Hi @WylAndy,

this seems to be a general Owncloud question/problem. Please consider reporting it to the [Owncloud Core Repository Issues](https://github.com/owncloud/core) or visit the [Owncloud forums](https://central.owncloud.org) to seek help!

Greetings

Felix
