### ISSUE TITLE
Logout if cas logout

### ISSUE THREAD

**Issue by pingou2712** [felixrupp/user_cas#80]
I'm french so poor english :P

**Is your feature request related to a problem? Please describe.**
When i logout from cas, the session stay in nextcloud... 

**Describe the solution you'd like**
I prefer if i logout my session cas, session nextcloud logout too... Or an option?
Is it possible?

**Comment by pingou2712** [comment]
OK after read your code, you seem to confuse:
-> logout CAS session if logout Nextcloud session
And:
-> logout Nextcloud session if logout CAS session

I send you a patch after ;)

**Comment by pingou2712** [comment]
done ++

**Comment by felixrupp** [comment]
Duplicate of #56

**Comment by felixrupp** [comment]
@pingou2712 Thanks for your solution, I’m going to review your code and merge it afterwards!
