### ISSUE TITLE
Iframe integration cause a loop on CAS ticket validation

### ISSUE THREAD

**Issue by jgribonvald** [felixrupp/user_cas#89]
**Describe the bug**
When including nexcloud in iframe into a webpage the CAS authentication make a loop on `https://xxxx.yyyyyy.zz/index.php/apps/user_cas/login?ticket=ST-XXXXX` page always with the same ticket until the browser stop it.

**To Reproduce**
1. Integrate nexcloud as iframe with the cas login direct link
2. Open the iframe with the browser console developper opened on network tab
3. See error

**Expected behavior**
The same behavior than without iframe.

**Software (please complete the following information):**
 - Server-OS: Debian 9
 - HTTP-Server Version: Apache 2.4.0
 - PHP-Version: PHP 7.1
 - ownCloud/Nextcloud Version: Nextcloud 17
- user_cas-Version: latest

**Additional context**

**Comment by jgribonvald** [comment]
My question also would be to know if something can block the auth ? Because the Content-Security-Policy is correctly set as we are doing it on other apps like that.
Thanks

**Comment by felixrupp** [comment]
Hi @jgribonvald 

thanks for your report, I’ll try to debug this.


Regards,
Felix

**Comment by jgribonvald** [comment]
This problem is fixed, Nextcloud require some configuration inside internal code to manage contextual Content-Security-Policies and other headers.

Sorry for the noise.
