### ISSUE TITLE
Support for Nextcloud 20

### ISSUE THREAD

**Issue by magikmw** [felixrupp/user_cas#95]
Nextcloud reports this app doesn't support Nextcloud 20.

**Comment by felixrupp** [comment]
@magikmw Thanks for your report, I am currently working on a release for Nextcloud 20.

**Comment by Emi94** [comment]
@felixrupp any update as to when will support for Nextcloud 20 come?

**Comment by felixrupp** [comment]
Hallo @magikmw 

the release version [1.8.7](https://github.com/felixrupp/user_cas/releases/tag/1.8.7) from today is now compatible with Nextcloud 20.


Regards,
Felix
