### ISSUE TITLE
Support for Nextcloud 21

### ISSUE THREAD

**Issue by Emi94** [felixrupp/user_cas#99]
Hi @felixrupp,

The app needs support for Nextcloud 21. I've enabled it on an NC 21 test instance and it seems to still work, but would be good to officially support version 21.

PS: NC 22 is already in beta so while you're at it maybe release a release for that as well? Have not tested against this version yet.

**Comment by adaugherity** [comment]
Yes, please!  This is preventing me from upgrading beyond 20, which is [now the oldest supported release](https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html), scheduled to expire in less than 3 months, and 22 is no longer beta.

I would also recommend upgrading the bundled phpCAS to 1.4.0, which will fix #98.

**Comment by Emi94** [comment]
This starts to look like a dead project. No response from the dev on other issues either and even in the past it took some time for the app to support new major versions of NC.

Because of this, I've started to look into this app https://apps.nextcloud.com/apps/oidc_login which supports even NC 22 and CAS supports the OIDC protocol https://apereo.github.io/cas/6.3.x/installation/OIDC-Authentication.html

**Comment by felixrupp** [comment]
Thanks for your contribution, I just released a bumped version including support for up to nextcloud 24.
